apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "app.chartname" . }}-configmap"
  namespace: {{ .Release.Namespace }}
data:
  signatory.conf: |
    proofConfig {
      issuerDid="did:web:wallet.walt.id:wallet-api:registry:portal"
      issuerVerificationMethod="todo"
      proofType="LD_PROOF"
      domain="wallet.walt.id"
      nonce="cfaf324fads"
      credentialsEndpoint={{ .Values.config.signatory.credentialsEndpoint | quote }}
    }
    templatesFolder: "vc-templates-runtime"
       