apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "app.chartname" . }}-signatory"
  namespace: {{ .Release.Namespace }}
data:
  signatory.conf: |
    {
      "proofConfig": {
        "issuerDid": {{ .Values.config.issuer.did | quote }},
        "proofType": {{ .Values.config.issuer.proofType | quote }},
        "ldSignatureType": "JsonWebSignature2020"
      },
      "templatesFolder": {{ .Values.config.issuer.templatesFolder | quote }}
    }
{{- range .Values.config.vcTemplates }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "app.chartname" $ }}-vc-template-{{ .name | lower }}"
  namespace: {{ $.Release.Namespace }}
data:
  {{ .name }}: {{ .value | toJson }}
{{- end }}