apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "app.chartname" . }}-configmap"
  namespace: {{ .Release.Namespace }}
data:
  signatory.conf: |
    {
      "proofConfig": {
        "issuerDid": {{ .Values.config.issuer.did | quote }},
        "proofType": {{ .Values.config.issuer.proofType | quote }}
      },
      "templatesFolder": {{ .Values.config.issuer.templatesFolder | quote }}
    }