apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: data-volume-claim
spec:
    accessModes:
      # - ReadWriteMany
      - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi