apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ template "app.chartname" . }}-data"
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.config.persistance.size }}