{{- if and .Values.clients (gt (len .Values.clients) 0) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "app.chartname" . }}-keycloak-client-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ include "app.revision" . }}
    app.kubernetes.io/part-of: rse
    {{ include "app.istioLabels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: {{ template "app.chartname" . }}-keycloak-client-init
        image: curlimages/curl:latest
        command: ["sh", "-c"]
        args:
        - |
          set -e

          wait-for-url() {
            echo "Testing $1"
            timeout -s TERM 200 sh -c \
            'while [[ "$(curl -k -s -o /dev/null -L -w ''%{http_code}'' ${0})" != "200" ]];\
            do echo "Waiting for ${0}" && sleep 20;\
            done' ${1}
            echo "OK!"
          }

          #################################################
          # Wait Keycloak to be up and running
          #################################################
          keycloak_url=http://{{ template "app.chartname" . }}-keycloak{{ default "/" .Values.keycloak.httpRelativePath }}
          wait-for-url ${keycloak_url}realms/master
          
          {{- range .Values.clients }}
          {{- $realm := .realm }}
          #################################################
          # Get Keycloak token
          #################################################
          response=$(curl -k -s -w "|%{http_code}" -X POST \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            -d "grant_type=password" \
            -d "client_id=admin-cli" \
            -d "username={{ .realmAdminUser }}" \
            -d "password={{ .realmAdminPass }}" \
            "${keycloak_url}realms/{{ $realm }}/protocol/openid-connect/token")
          body=$(echo $response | awk -F '|' '{print $1}')
          code=$(echo $response | awk -F '|' '{print $2}')
          if [ $code -eq 200 ]; then
            echo "Got Keycloak token"
          else
            echo "Bad Request"
            exit 1
          fi

          access_token=$(echo $body | grep -m1 -oE '"access_token":"[^"]+"' | awk -F ':' '{gsub(/"/,"",$2); print $2}')

          {{- range .issuers }}
          #################################################
          # Register client for issuer {{ .did }}
          #################################################
          echo "DEBUG: Attempting to register SIOP client for issuer {{ .did }}"
          echo "DEBUG: Using URL: ${keycloak_url}realms/{{ $realm }}/clients-registrations/SIOP-2"
          
          response=$(curl -k -s -w "|%{http_code}" -X POST \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer $access_token" \
            -d "{
              \"name\": \"siop-client\",
              \"clientDid\": \"{{ .did }}\",
              \"description\": \"Client to issue Verifiable Credentials.\",
              \"supportedVCTypes\": [
                {{- range $i, $elem := .supportedVCTypes }}
                {{- if gt $i 0 }},{{- end }}
                {
                  \"type\": \"{{ $elem.type }}\",
                  \"format\": \"{{ $elem.format }}\" 
                }
                {{- end }}
              ],
              \"expiryInMin\": 3600,
              \"claims\": {
                {{- if .claims }}
                {{- $last := sub (len .claims) 1 }}
                {{- range $i, $elem := .claims }}
                \"{{ $elem.vcType }}_claims\": \"{{ $elem.claims }}\"
                {{- if ne $i $last }},{{- end }}
                {{- end }}
                {{- end }}
              },
              \"additionalClaims\": {
                {{- if .additionalClaims }}
                {{- $last := sub (len .additionalClaims) 1 }}
                {{- range $i, $elem := .additionalClaims }}
                \"{{ $elem.vcType }}_claims\": \"{{ $elem.claims }}\"
                {{- if ne $i $last }},{{- end }}
                {{- end }}
                {{- end }}
              }
            }" \
            "${keycloak_url}realms/{{ $realm }}/clients-registrations/SIOP-2")
          body=$(echo $response | awk -F '|' '{print $1}')
          code=$(echo $response | awk -F '|' '{print $2}')
          echo "DEBUG: SIOP client registration response code: $code"
          echo "DEBUG: SIOP client registration response body: $body"
          echo "DEBUG: SIOP client registration response response: $response"

          if [ $code -eq 201 ]; then
            echo "Client {{ .idpClientName }} registered successfully"
          elif [ $code -eq 409 ] || [[ "$body" == *"already exists"* ]] || [[ "$body" == *"duplicate"* ]]; then
            echo "WARNING: SIOP client already exists, continuing... (HTTP $code)"
          elif [ $code -eq 500 ] && [[ "$body" == *"unknown_error"* ]]; then
            echo "WARNING: SIOP client registration failed with server error, likely already exists. Continuing... (HTTP $code)"
          else
            echo "ERROR: Failed to register SIOP client. HTTP code: $code, Response: $body"
            exit 1
          fi
          {{- end }}

          {{- range .identityProviders }}
          #################################################
          # Register client {{ .clientName }}
          #################################################
          echo "DEBUG: Attempting to register identity provider client {{ .clientName }}"
          echo "DEBUG: Using URL: {{ .clientRegisterUrl }}"
          
          response=$(curl -k -s -w "|%{http_code}" -X POST \
            -H 'Content-Type: application/json' \
            -d "{
              \"client_name\": \"{{ .clientName }}\",
              \"redirect_uris\": [ \"{{ .redirectUri }}\" ],
              \"all_redirect_uris\": false
            }" \
            "{{ .clientRegisterUrl }}")
          body=$(echo $response | awk -F '|' '{print $1}')
          code=$(echo $response | awk -F '|' '{print $2}')
          echo "DEBUG: Identity provider client registration response code: $code"
          echo "DEBUG: Identity provider client registration response body: $body"
          if [ $code -eq 201 ]; then
            echo "Client {{ .clientName }} registered successfully"
          elif [ $code -eq 409 ] || [[ "$body" == *"already exists"* ]] || [[ "$body" == *"duplicate"* ]]; then
            echo "WARNING: Identity provider client {{ .clientName }} already exists, continuing... (HTTP $code)"
          else
            echo "ERROR: Failed to register identity provider client {{ .clientName }}. HTTP code: $code, Response: $body"
            exit 1
          fi

          client_id=$(echo $body | grep -m1 -oE '"client_id": "[^"]+"' | awk -F ': ' '{gsub(/"/,"",$2); print $2}')
          client_secret=$(echo $body | grep -m1 -oE '"client_secret": "[^"]+"' | awk -F ': ' '{gsub(/"/,"",$2); print $2}')

          #################################################
          # Get idp {{ .alias }} metadata
          #################################################
          echo "DEBUG: Getting metadata for IDP {{ .alias }}"
          echo "DEBUG: Using discovery URL: {{ .oidcDiscoveryUrl }}"
          
          response=$(curl -k -s -w "|%{http_code}" -X GET \
            -H 'Content-Type: application/json' \
            "{{ .oidcDiscoveryUrl }}")
          body=$(echo $response | awk -F '|' '{print $1}')
          code=$(echo $response | awk -F '|' '{print $2}')
          echo "DEBUG: IDP metadata response code: $code"
          if [ $code -eq 200 ]; then
            echo "Got idp {{ .alias }} metadata successfully"
          else
            echo "ERROR: Failed to get IDP metadata. HTTP code: $code, Response: $body"
            exit 1
          fi

          authorization_url=$(echo $body | grep -m1 -oE '"authorization_endpoint": "[^"]+"' | awk -F ': ' '{gsub(/"/,"",$2); print $2}')
          token_url=$(echo $body | grep -m1 -oE '"token_endpoint": "[^"]+"' | awk -F ': ' '{gsub(/"/,"",$2); print $2}')
          user_info_url=$(echo $body | grep -m1 -oE '"userinfo_endpoint": "[^"]+"' | awk -F ': ' '{gsub(/"/,"",$2); print $2}')
          issuer=$(echo $body | grep -m1 -oE '"issuer": "[^"]+"' | awk -F ': ' '{gsub(/"/,"",$2); print $2}')
          jwks_url=$(echo $body | grep -m1 -oE '"jwks_uri": "[^"]+"' | awk -F ': ' '{gsub(/"/,"",$2); print $2}')
          
          #################################################
          # Register idp {{ .alias }} in Keycloak
          #################################################
          echo "DEBUG: Registering IDP {{ .alias }} in Keycloak"
          echo "DEBUG: Using Keycloak admin URL: ${keycloak_url}admin/realms/{{ $realm }}/identity-provider/instances"
          
          response=$(curl -k -s -w "|%{http_code}" -X POST \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer $access_token" \
            -d "{
              \"providerId\": \"oidc\",
              \"alias\": \"{{ .alias }}\",
              \"displayName\": \"{{ .displayName }}\",
              \"config\": {
                \"authorizationUrl\": \"${authorization_url}\",
                \"tokenUrl\": \"${token_url}\",
                \"userInfoUrl\": \"${user_info_url}\",
                \"issuer\": \"${issuer}\",
                \"jwksUrl\": \"${jwks_url}\",
                \"clientAuthMethod\": \"client_secret_basic\",
                \"clientId\": \"${client_id}\",
                \"clientSecret\": \"${client_secret}\",
                \"defaultScope\": \"{{ .defaultScope }}\"
              }
            }" \
            "${keycloak_url}admin/realms/{{ $realm }}/identity-provider/instances")
          body=$(echo $response | awk -F '|' '{print $1}')
          code=$(echo $response | awk -F '|' '{print $2}')
          echo "DEBUG: IDP registration response code: $code"
          echo "DEBUG: IDP registration response body: $body"
          if [ $code -eq 201 ]; then
            echo "IDP {{ .alias }} registered successfully"
          elif [ $code -eq 409 ] || [[ "$body" == *"already exists"* ]] || [[ "$body" == *"duplicate"* ]]; then
            echo "WARNING: IDP {{ .alias }} already exists, continuing... (HTTP $code)"
          else
            echo "ERROR: Failed to register IDP {{ .alias }}. HTTP code: $code, Response: $body"
            exit 1
          fi
          {{- end }}

          {{- end }}

          exit 0
      restartPolicy: Never
  backoffLimit: 4
  {{- end }}




