keycloak:
  image:
    tag: 26.0.7-debian-12-r1
  command: 
    - /bin/sh
  args:
    - -c
    - |
      for f in /opt/dataspace4health.local/certs/*.pem; do 
        echo "Adding certificate $f to keystore"
        certname=$(echo $(basename $f) | sed 's|.crt||g' )
        mkdir -p /tmp/truststores
        keytool -import -trustcacerts -noprompt -storepass changeit -alias $(basename $f) -file $f -keystore /tmp/truststores/cacerts
      done
      
      JAVA_OPTS="-Djavax.net.ssl.trustStore=/tmp/truststores/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
      echo "Starting Keycloak"
      JAVA_OPTS=${JAVA_OPTS} /opt/bitnami/scripts/keycloak/entrypoint.sh /opt/bitnami/scripts/keycloak/run.sh
  auth:
    adminUser: admin
    adminPassword: "xfsc4Ntt!"
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"
    - name: KC_FEATURES
      value: token-exchange,admin-fine-grained-authz # required by Walt.Id Wallet API
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
  extraVolumeMounts:
    - name: config
      mountPath: "/opt/bitnami/keycloak/data/import/iam-realm.json"
      subPath: "iam-realm.json"
      readOnly: true
    - name: dataspace4health-local
      mountPath: "/opt/dataspace4health.local/certs/dataspace4health.local.pem"
      subPath: "dataspace4health.local.pem"
      readOnly: true
  extraVolumes:
    - name: config
      configMap:
        name: iam-keycloak-configmap
        items:
        - key: "iam-realm.json"
          path: "iam-realm.json"
    - name: dataspace4health-local
      secret:
        secretName: dataspace4health.local
        items:
        - key: "ca.crt"
          path: "dataspace4health.local.pem"
        defaultMode: 420
  # logging:
  #   level: "DEBUG,io.quarkus:INFO,freemarker.cache:INFO,liquibase:INFO,org.hibernate:INFO,org.infinispan:INFO,org.keycloak.services.scheduled:INFO,org.keycloak.transaction:INFO,io.netty.buffer.PoolThreadCache:INFO,org.keycloak.models.sessions.infinispan:INFO"
  production: false
  proxy: edge
  httpRelativePath: "/iam/"
  postgresql:
    enabled: true
    auth: 
      database: iam
      username: iam 
      password: "xfsc4Ntt!"
      postgresPassword: "xfsc4Ntt!"
    primary:
      persistence:
        size: 5Gi
  ingress:
    enabled: true
    extraHosts:
      - name: ""
    pathType: Prefix
    path: /iam
    extraTls:
      - secretName: dataspace4health.local
        hosts:
          - dataspace4health.local