keycloak:
  command: 
    - /bin/sh
  args:
    - -c
    - |
      for f in /opt/dataspace4health.local/certs/*.crt; do 
        echo "Adding certificate $f to keystore"
        certname=$(echo $(basename $f) | sed 's|.crt||g' )
        mkdir -p /tmp/truststores
        keytool -import -trustcacerts -noprompt -storepass changeit -alias ${certname} -file $f -keystore /tmp/truststores/cacerts
      done

      domains=$(echo "${TRUSTED_DOMAINS}" | tr ',' ' ')
      for domain in ${domains}; do
        echo "Processing domain: $domain"
      
        # Get TLS certificate
        echo | openssl s_client -showcerts -connect ${domain}:443 2>/dev/null | \
          openssl x509 -outform PEM > "/tmp/${domain}.crt"
      
        # Import TLS certificate to keystore
        keytool -import -trustcacerts -noprompt -storepass changeit \
          -alias "${domain}" \
          -file "/tmp/${domain}.crt" \
          -keystore /tmp/truststores/cacerts
      
        # Clean up
        rm -f "/tmp/${item}.crt"
      done
      
      JAVA_OPTS="-Djavax.net.ssl.trustStore=/tmp/truststores/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
      echo "Starting Keycloak"
      JAVA_OPTS=${JAVA_OPTS} /opt/bitnami/scripts/keycloak/entrypoint.sh /opt/bitnami/scripts/keycloak/run.sh
  auth:
    adminUser: admin
    adminPassword: "xfsc4Ntt!"
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
  extraVolumeMounts:
    - name: config
      mountPath: "/opt/bitnami/keycloak/data/import/iam-realm.json"
      subPath: "iam-realm.json"
      readOnly: true
    - name: dataspace4health-local
      mountPath: "/opt/dataspace4health.local/certs/dataspace4health.local.crt"
      subPath: "dataspace4health.local.crt"
      readOnly: true
  extraVolumes:
    - name: config
      configMap:
        name: iam-keycloak-configmap
        items:
        - key: "iam-realm.json"
          path: "iam-realm.json"
    - name: dataspace4health-local
      secret:
        secretName: dataspace4health.local
        items:
        - key: "ca.crt"
          path: "dataspace4health.local.crt"
        defaultMode: 420
  # logging:
  #   level: "DEBUG,io.quarkus:INFO,freemarker.cache:INFO,liquibase:INFO,org.hibernate:INFO,org.infinispan:INFO,org.keycloak.services.scheduled:INFO,org.keycloak.transaction:INFO,io.netty.buffer.PoolThreadCache:INFO,org.keycloak.models.sessions.infinispan:INFO"
  production: false
  proxy: edge
  httpRelativePath: "/iam/"
  postgresql:
    enabled: true
    image:
      registry: bitnamilegacy
      repository: postgresql
      tag: 16.2.0-debian-12-r8
    auth: 
      database: iam
      username: iam 
      password: "xfsc4Ntt!"
      postgresPassword: "xfsc4Ntt!"
    primary:
      persistence:
        size: 5Gi
  ingress:
    enabled: true
    extraHosts:
      - name: ""
    pathType: Prefix
    path: /iam
    extraTls:
      - secretName: dataspace4health.local
        hosts:
          - dataspace4health.local