{{- range $i, $elem := .Values.keycloak.ingress.replacePath }}
# Replace path with regex
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.chartname" . }}-keycloak-replacepathregex-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  replacePathRegex:
    regex: {{ $elem.regex }}
    replacement: {{ $elem.replacement }}
{{- end }}
{{- range $i, $elem := .Values.keycloak.ingress.replaceBody }}
---
# Replace body with regex
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.chartname" $ }}-keycloak-replacebodyregex-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  plugin:
    rewriteBody:
      rewrites:
      - regex: {{ $elem.regex | quote }}
        replacement: {{ $elem.replacement | quote }}
      logLevel: {{ default $elem.logLevel 0 }}
      {{- if $elem.monitoring }}
      monitoring:
        {{- if $elem.monitoring.methods }}
        methods:
          {{- range $index, $element := $elem.monitoring.methods }}
          - {{ $element | quote }}
          {{- end }}
        {{- end }}
        {{- if $elem.monitoring.types }}
        types:
          {{- range $index, $element := $elem.monitoring.types }}
          - {{ $element | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
{{- end }}
{{- range $i, $elem := .Values.keycloak.ingress.replaceHeader }}
---
# Replace Headers with regex
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.chartname" $ }}-keycloak-replaceheaderregex-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  plugin:
    rewriteHeaders:
      rewrites:
        - header: {{ $elem.header }}
          regex: {{ $elem.regex }}
          replacement: {{ $elem.replacement }}
{{- end }}
{{- range $i, $elem := .Values.keycloak.ingress.headers }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.chartname" $ }}-keycloak-headers-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  headers:
{{ toYaml $elem.headers | indent 4 }}
{{- end }}
{{- range $i, $elem := .Values.keycloak.ingress.clientMaxBodySize }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.chartname" $ }}-keycloak-client-max-body-size-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: {{ $elem.clientMaxBodySize }}
{{- end }}
