iam: 
  keycloak:
    imagePullSecrets: 
      - name: acr-creds
    initContainers:
    - name: iam-keycloak-init
      image: curlimages/curl:latest
      imagePullPolicy: IfNotPresent
      env:
      - name: VCISSUER_ISSUER_DID
        value: did:web:dataspace4health.local:wallet:api:wallet-api:registry:0
      command: ["sh", "-c"]
      args:
        - |
          # wait for waltid issuer to be available
          url=https://$(echo $VCISSUER_ISSUER_DID | sed 's|did:web:||' | sed 's|:|/|g')/did.json
          wait-for-url() {
            echo "Testing $1"
            timeout -s TERM 200 sh -c \
            'while [[ "$(curl -k -s -o /dev/null -L -w ''%{http_code}'' ${0})" != "200" ]];\
            do echo "Waiting for ${0}" && sleep 20;\
            done' ${1}
            echo "OK!"
            curl -kI $1
          }
          wait-for-url ${url}
    - name: iam-keycloak-vc-issuer-init
      #image: quay.io/fiware/keycloak-vc-issuer:1.0.3
      image: dh4sdev.azurecr.io/keycloak-vc-issuer:0.0.1
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /target
        name: fiware-lib


# idp-ui:
#   image:
#     repository: dh4sdev.azurecr.io
#     name: walletid-idpkit
#     tag: "0.0.1"
#     pullSecrets: acr-creds

# issuer-api:
#   image:
#     repository: dh4sdev.azurecr.io
#     name: keycloak-vc-issuer
#     tag: "0.0.1"
#     pullSecrets: acr-creds

wallet-ui: 
  image:
    repository: dh4sdev.azurecr.io
    name: walletid-identity-ui
    tag: "0.0.1"
    pullSecrets: acr-creds

wallet-api:
  image:
    repository: dh4sdev.azurecr.io
    name: walletid-identity-api
    tag: "0.0.1"
    pullSecrets: acr-creds