wallet-ui: 
  image:
    repository: dh4sdev.azurecr.io
    name: walletid-identity-ui
    tag: "0.0.1"
    pullSecrets: acr-creds

wallet-api:
  image:
    repository: dh4sdev.azurecr.io
    name: walletid-identity-api
    tag: "0.0.1"
    pullSecrets: acr-creds