apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "app.chartname" . }}-configmap"
  namespace: {{ .Release.Namespace }}
data:
  # OIDC Manager configuration #      "keyId": "715b3ebf65074f1183a48c4b7c8e311c",
  idp-config.json: |
    {
      "externalUrl": {{ .Values.config.externalUrl | quote }},
      "openClientRegistration": true,
      "fallbackAuthorizationMode": "SIOP",
      "claimConfig": {
        "vc_mappings": [
          {
            "scope": [ "profile" ],
            "claim": "name",
            "credentialType": "NaturalPerson",
            "valuePath": "$.credentialSubject.firstName $.credentialSubject.familyName"
          },
          {
            "scope": [ "profile" ],
            "claim": "family_name",
            "credentialType": "NaturalPerson",
            "valuePath": "$.credentialSubject.familyName"
          },
          {
            "scope": [ "profile" ],
            "claim": "given_name",
            "credentialType": "NaturalPerson",
            "valuePath": "$.credentialSubject.firstName"
          },
          {
            "scope": [ "email" ],
            "claim": "email",
            "credentialType": "NaturalPerson",
            "valuePath": "$.credentialSubject.email"
          },
          {
            "scope": [ "profile" ],
            "claim": "contract",
            "credentialType": "gx:ServiceOffering",
            "valuePath": "$.credentialSubject[0].gx:name"
          }
        ],
        "default_vp_token_claim": {
          "presentation_definition": {
            "id": "1",
            "submission_requirements": [
              {
                "name": "Require both NaturalPerson and ServiceOffering",
                "rule": "pick",
                "from": "required-credentials"
              }
            ],
            "input_descriptors": [
              {
                "id": "natural-person",
                "group": ["required-credentials"],
                "name": "Natural Person Credential",
                "constraints": {
                  "fields": [
                    {
                      "path": ["$.type"],
                      "filter": {
                        "type": "array",
                        "contains": {
                          "const": "NaturalPerson"
                        }
                      }
                    }
                  ]
                }
              },
              {
                "id": "service-offering",
                "group": ["required-credentials"],
                "name": "Service Offering Credential",
                "constraints": {
                  "fields": [
                    {
                      "path": ["$.type"],
                      "filter": {
                        "type": "array",
                        "contains": {
                          "const": "gx:ServiceOffering"
                        }
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      }
    }
  # SIOP Manager configuration (SIOP derived from the Verifer Manager)
  verifier-config.json: |
    {
      "verifierUiUrl": "{{ .Values.config.verifierUiUrl }}",
      "verifierApiUrl": "{{ .Values.config.verifierApiUrl }}",
      "additionalPolicies": [
      ],
      "wallets": {
        "local": {
          "id": "local",
          "url": "{{ .Values.config.walletUrl }}",
          "presentPath": "api/siop/initiatePresentation/",
          "receivePath" : "api/siop/initiateIssuance/",
          "description": "Local web wallet"
        }
      }
    }
  nft-config.json: |
    {
    }