apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "app.chartname" . }}-configmap"
  namespace: {{ .Release.Namespace }}
data:
  issuer-config.json: |
    {
      "issuerUiUrl": "https://issuer.walletkit.walt.id",
      "issuerApiUrl": "https://issuer.walletkit.walt.id/issuer-api/default",
      "issuerClientName": "walt.id Issuer Portal",
      "wallets": {
        "walt.id": {
          "id": "walt.id",
          "url": "https://wallet.walt.id",
          "presentPath": "api/siop/initiatePresentation/",
          "receivePath" : "api/siop/initiateIssuance/",
          "description": "walt.id web wallet"
        }
      }
    }
  verifier-config.json: |
    {
      "verifierUiUrl": "https://verifier.walletkit.walt.id",
      "verifierApiUrl": "https://verifier.walletkit.walt.id/verifier-api/default",
      "wallets": {
        "walt.id": {
          "id": "walt.id",
          "url": "https://wallet.walt.id",
          "presentPath": "api/siop/initiatePresentation/",
          "receivePath" : "api/siop/initiateIssuance/",
          "description": "walt.id web wallet"
        }
      }
    }
  wallet-config.json: |
    {
      "walletUiUrl": "https://wallet.walt.id",
      "walletApiUrl": "https://wallet.walt.id/api",
      "issuers": {
        "walt.id": {
          "id": "walt.id",
          "url": "https://wallet.walt.id/issuer-api/default/oidc",
          "description": "walt.id Issuer Portal"
        },
        "yes.com": {
          "id": "yes.com",
          "url": "https://demo.sandbox.yes.com/essif/issuer/c2id",
          "description": "yes.com Bank ID issuer"
        }
      }
    }