apiVersion: v1
kind: Service
metadata:
  name: "{{ template "app.chartname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  {{- range .Values.config.http.ports }}
  - name: {{ .name }}
    targetPort: {{ .containerPort }}
    port: {{ .containerPort }}
  {{- end }}
  selector:
    {{- include "app.selectorLabels" $ | nindent 4 }}